#Материал шприца
Material: SCUTE
#Название для шприца
Name: "&fМедицинский шприц"
#Моментальное восстановление здоровья после использования шприца
Instant_health_recovery: 4
#Восстановление здоровья в течении какого-то времени после использования шприца
Interval_health_recovery: 4
#Значение для текстур-пака
Custom_model_data: 1
#Стак по одному предмету или нет false/true
One_item_in_stack: true


reload_config_message: "&aПлагин успешно перезагружен!"
